### ISSUE TITLE
大佬你好 ，这个运行之后出现的文字是乱码应该怎么处理呢

### ISSUE THREAD

**Issue by SuShangQing** [QuanQuan-CHO/Bilibili-Genshin-Impact-Live-Grab-Tool#1]

**Comment by liqwang** [comment]
截个图

**Comment by SuShangQing** [comment]
> 截个图
![@)4ULGK5E_1%1_B$3BLTVMR](https://user-images.githubusercontent.com/102420864/189037746-4931d6d3-2800-4452-8644-979c00243ff7.png)
大概这样的

**Comment by liqwang** [comment]
是编码问题，试试这个https://www.cnblogs.com/letGoGo/articles/13576521.html

**Comment by SuShangQing** [comment]
已解决，谢谢大佬
