### ISSUE TITLE
下载了openjdk 这个livegrabtool从哪里打开啊 找不到

### ISSUE THREAD

**Issue by geymerone** [QuanQuan-CHO/Bilibili-Genshin-Impact-Live-Grab-Tool#5]

**Comment by liqwang** [comment]
你要先用Git克隆这个仓库

**Comment by geymerone** [comment]
这个操作很难吗 不会弄 有模板吗




fishQAQ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuanQuan-CHO/Bilibili-Genshin-Impact-Live-Grab-Tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月22日(星期天) 凌晨0:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QuanQuan-CHO/Bilibili-Genshin-Impact-Live-Grab-Tool] 下载了openjdk 这个livegrabtool从哪里打开啊 找不到 (Issue #5)





 
你要先用Git克隆这个仓库

**Comment by liqwang** [comment]
加我QQ 836200779
